name: bocadito
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  flutter_launcher_icons: ^0.14.1
  go_router: ^14.3.0
  sliding_clipped_nav_bar: ^3.1.1
  provider: ^6.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  location: ^7.0.1
  http: ^1.2.2
  shared_preferences: ^2.3.3

dev_dependencies:
  change_app_package_name: ^1.1.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/galaxy.jpg"
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - assets/
